// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZviy_V_5QAg8kAJxD9ZU0oGQg0oB0u5M',
    appId: '1:640340395011:web:47a2f0acabc5752a66ba36',
    messagingSenderId: '640340395011',
    projectId: 'todoappfirebase-ff597',
    authDomain: 'todoappfirebase-ff597.firebaseapp.com',
    storageBucket: 'todoappfirebase-ff597.appspot.com',
    measurementId: 'G-WB3CMJ5KWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVufDwPXsqD48Rt6quim71GRPi16gkUw',
    appId: '1:640340395011:android:36a7b0e429f653e466ba36',
    messagingSenderId: '640340395011',
    projectId: 'todoappfirebase-ff597',
    storageBucket: 'todoappfirebase-ff597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaZnweBPdR1keYVm8FWpJ87Ilkcj0QZM',
    appId: '1:640340395011:ios:fea10c267041d52366ba36',
    messagingSenderId: '640340395011',
    projectId: 'todoappfirebase-ff597',
    storageBucket: 'todoappfirebase-ff597.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaZnweBPdR1keYVm8FWpJ87Ilkcj0QZM',
    appId: '1:640340395011:ios:9cb0d5243d5554af66ba36',
    messagingSenderId: '640340395011',
    projectId: 'todoappfirebase-ff597',
    storageBucket: 'todoappfirebase-ff597.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
